# Generated by Django 3.2.25 on 2025-11-30 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.CharField(choices=[('2025-12-01 15:41:37.562926', '2025-12-01 15:41:37.562926'), ('2025-12-02 15:41:37.562926', '2025-12-02 15:41:37.562926'), ('2025-12-03 15:41:37.562926', '2025-12-03 15:41:37.562926'), ('2025-12-04 15:41:37.562926', '2025-12-04 15:41:37.562926'), ('2025-12-05 15:41:37.562926', '2025-12-05 15:41:37.562926')], default=datetime.datetime(2025, 12, 1, 15, 41, 37, 562926), max_length=26),
        ),
    ]
