# Generated by Django 5.2.14 on 2026-05-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed')], default='pending', max_length=20),
        ),
    ]
