# Generated by Django 3.2.25 on 2025-12-06 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_appointment_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.CharField(choices=[('08.12.25', '08.12.25'), ('09.12.25', '09.12.25'), ('10.12.25', '10.12.25'), ('11.12.25', '11.12.25'), ('12.12.25', '12.12.25')], default=datetime.datetime(2025, 12, 7, 18, 49, 35, 995353), max_length=26),
        ),
    ]
